// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2ua2zB6CMyb6iVgTKOypqp-mH6o__a0',
    appId: '1:45153029931:web:966ec477dcac6f7f677f6e',
    messagingSenderId: '45153029931',
    projectId: 'smartclassroom-b40d1',
    authDomain: 'smartclassroom-b40d1.firebaseapp.com',
    databaseURL: 'https://smartclassroom-b40d1-default-rtdb.firebaseio.com',
    storageBucket: 'smartclassroom-b40d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQF17nlbaA6SKibxOY1sT6hxBVNvnvKRk',
    appId: '1:45153029931:android:9358f227cd2a1a9e677f6e',
    messagingSenderId: '45153029931',
    projectId: 'smartclassroom-b40d1',
    databaseURL: 'https://smartclassroom-b40d1-default-rtdb.firebaseio.com',
    storageBucket: 'smartclassroom-b40d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQ4o4MtxwwPWmgzyVoDlyko7AOTB8d2o',
    appId: '1:45153029931:ios:b6cd867be161e108677f6e',
    messagingSenderId: '45153029931',
    projectId: 'smartclassroom-b40d1',
    databaseURL: 'https://smartclassroom-b40d1-default-rtdb.firebaseio.com',
    storageBucket: 'smartclassroom-b40d1.firebasestorage.app',
    iosBundleId: 'com.gapf.smartclassrom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQ4o4MtxwwPWmgzyVoDlyko7AOTB8d2o',
    appId: '1:45153029931:ios:b6cd867be161e108677f6e',
    messagingSenderId: '45153029931',
    projectId: 'smartclassroom-b40d1',
    databaseURL: 'https://smartclassroom-b40d1-default-rtdb.firebaseio.com',
    storageBucket: 'smartclassroom-b40d1.firebasestorage.app',
    iosBundleId: 'com.gapf.smartclassrom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2ua2zB6CMyb6iVgTKOypqp-mH6o__a0',
    appId: '1:45153029931:web:f509da4c22f5300d677f6e',
    messagingSenderId: '45153029931',
    projectId: 'smartclassroom-b40d1',
    authDomain: 'smartclassroom-b40d1.firebaseapp.com',
    databaseURL: 'https://smartclassroom-b40d1-default-rtdb.firebaseio.com',
    storageBucket: 'smartclassroom-b40d1.firebasestorage.app',
  );
}
